## Casos de Teste

| Preencher o campo nome no formulario adicionar carteira de motorista |                                                                                         | 1                                                                               | 2               | 3                                                 | 4                                                                                                            | 5         |
| :------------------------------------------------------------------- | :-------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------ | :-------------- | :------------------------------------------------ | :----------------------------------------------------------------------------------------------------------- | :-------- |
|  ID do caso de teste                                                 | Nome do caso de teste                                                                   | Pré-condição                                                                    | Número da etapa | Descrição da etapa                                | Resultado esperado                                                                                           | Status    |
| CT-1                                                                 | O campo "Nome" deve aceitar nomes com 2 caracteres                                      | O formulário para solicitar um serviço de compartilhamento de carro está aberto | 1               | Clique no botão "Adicionar carteira de motorista" | Não deve haver uma mensagem de erro no campo "Nome".                                                         | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com o valor "Jo"          |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome" clicando fora dele  |                                                                                                              |           |
| CT-2                                                                 | O campo "Nome" deve aceitar nomes com 14 caracteres                                     | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Não deve haver uma mensagem de erro no campo "Nome".                                                         | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Maximilianiano"      |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-3                                                                 | O campo "Nome" deve rejeitar nomes com 1 caractere                                      | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "A"                   |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-4                                                                 | O campo "Nome" deve rejeitar nomes com mais de 14 caracteres                            | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Rumpelstiltskin"     |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-5                                                                 | O campo "Nome" deve aceitar nomes com comprimento médio (valor válido dentro da classe) | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Não deve haver uma mensagem de erro no campo "Nome".                                                         | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Ricardo"             |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-6                                                                 | O campo "Nome" deve aceitar apenas letras latinas                                       | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Não deve haver uma mensagem de erro no campo "Nome".                                                         | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Maria"               |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-7                                                                 | O campo "Nome" deve validar caracteres acentuados                                       | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Não deve haver uma mensagem de erro no campo "Nome".                                                         | Reprovado |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "João"                |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-8                                                                 | O campo "Nome" deve aceitar letras com espaços                                          | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Não deve haver uma mensagem de erro no campo "Nome".                                                         | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Maria Madalena"      |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-9                                                                 | O campo "Nome" deve rejeitar nome com espaço no início                                  | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Reprovado |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com " Maria"              |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-10                                                                | O campo "Nome" deve rejeitar nome com espaço no fim                                     | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Reprovado |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Maria "              |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-11                                                                | O campo "Nome" deve rejeitar nome com espaços duplos                                    | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Reprovado |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com " Maria "             |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-12                                                                | O campo "Nome" deve aceitar letras com traço                                            | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Não deve haver uma mensagem de erro no campo "Nome".                                                         | Reprovado |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Ana-Maria"           |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-13                                                                | O campo "Nome" deve rejeitar nome com hífen no início                                   | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "-Maria"              |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-14                                                                | O campo "Nome" deve rejeitar nome com hífen no fim                                      | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Maria-"              |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-15                                                                | O campo "Nome" deve rejeitar nome com hífen duplo                                       | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Maria--Silva"        |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-16                                                                | O campo "Nome" deve rejeitar números                                                    | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Maria1"              |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-17                                                                | O campo "Nome" deve rejeitar caracteres especiais                                       | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "Ana!"                |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-18                                                                | O campo "Nome" deve rejeitar alfabetos não latinos                                      | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com "李"                   |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-19                                                                | O campo "Nome" deve rejeitar campo vazio                                                | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Aprovado  |
|                                                                      |                                                                                         |                                                                                 | 2               | Não preencha nada no campo "Nome"                 |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
| CT-20                                                                | O campo "Nome" deve rejeitar campo preenchido apenas com espaços                        | Formulário aberto                                                               | 1               | Clique no botão "Adicionar carteira de motorista" | Deve ser exibida a mensagem de erro "Insira um nome correto". O campo "Nome" deve ficar marcado em vermelho. | Reprovado |
|                                                                      |                                                                                         |                                                                                 | 2               | Preencha o campo "Nome" com " "                   |                                                                                                              |           |
|                                                                      |                                                                                         |                                                                                 | 3               | Remova o foco do campo "Nome"                     |                                                                                                              |           |
